//! 初始化命令实现

use super::types::*;
use crate::utils::i18n::{t, t1};
use std::fs;
use std::path::Path;

const E_INIT_CURRENT_DIR: &str = "E_INIT_CURRENT_DIR";
const E_INIT_WRITE_CONFIG: &str = "E_INIT_WRITE_CONFIG";
const E_INIT_CREATE_DIR: &str = "E_INIT_CREATE_DIR";
const E_INIT_CREATE_CONFIG_FILE: &str = "E_INIT_CREATE_CONFIG_FILE";
const E_INIT_READ_CONFIG_FILE: &str = "E_INIT_READ_CONFIG_FILE";
const E_INIT_APPEND_CONFIG_FILE: &str = "E_INIT_APPEND_CONFIG_FILE";
const E_INIT_HOOKS_ALREADY_INSTALLED: &str = "E_INIT_HOOKS_ALREADY_INSTALLED";
const E_INIT_WRITE_HOOK_FILE: &str = "E_INIT_WRITE_HOOK_FILE";
const E_INIT_SET_AUTORUN: &str = "E_INIT_SET_AUTORUN";
const E_INIT_SET_AUTORUN_FAILED: &str = "E_INIT_SET_AUTORUN_FAILED";

/// VCS 透明拦截命令列表
const VCS_COMMANDS: &[&str] = &[
    "git", "svn", "hg", "p4", "bzr", "cvs", "fossil", "darcs", "gh", "glab", "az", "repo",
];

/// 构建工具透明拦截命令列表
const BUILD_COMMANDS: &[&str] = &[
    "cargo",
    "make",
    "cmake",
    "gradle",
    "gradlew",
    "mvn",
    "npm",
    "yarn",
    "pnpm",
    "pip",
    "pip3",
    "go",
    "docker",
    "docker-compose",
    "kubectl",
    "helm",
    "terraform",
    "ansible",
    "ansible-playbook",
    "pulumi",
    "aws",
    "gcloud",
    "pytest",
    "dotnet",
    "ninja",
    "bazel",
    "meson",
    "ctest",
    "poetry",
    "uv",
    "bun",
    "deno",
    "composer",
    "bundle",
    "flutter",
    "dart",
    "swift",
    "xcodebuild",
];

/// 执行初始化命令
pub fn run_init(options: InitOptions) -> Result<InitResult, String> {
    let cwd = std::env::current_dir().map_err(|e| format!("{E_INIT_CURRENT_DIR}:{e}"))?;

    // 检测项目信息
    let project_info = detect_project_type(&cwd);

    // 生成配置文件
    let config_path = cwd.join(".tokenslim.toml");
    let config_created = if config_path.exists() && !options.force {
        false
    } else {
        let config_content = generate_config(&project_info);
        if options.dry_run {
            println!("{}", config_content);
            false
        } else {
            fs::write(&config_path, config_content)
                .map_err(|e| format!("{E_INIT_WRITE_CONFIG}:{e}"))?;
            true
        }
    };

    // 安装 shell hooks (可选)
    let hooks_installed = if options.install_hooks {
        let shell = options.hook_shell.clone().unwrap_or_else(detect_shell);
        match install_hooks_simple(&shell, options.dry_run) {
            Ok(_) => true,
            Err(e) => {
                if e == E_INIT_HOOKS_ALREADY_INSTALLED {
                    // Silent success or print info
                    true
                } else {
                    eprintln!("{}", t1("core_init_hooks_install_failed", e));
                    false
                }
            }
        }
    } else {
        false
    };

    // 构建结果消息
    let mut message = t("core_init_success").to_string();
    if !config_created {
        if config_path.exists() {
            message.push_str(t("core_init_config_exists_force"));
        } else {
            message.push_str(t("core_init_dry_run_no_files"));
        }
    }

    Ok(InitResult {
        config_created,
        config_path: config_path.to_string_lossy().to_string(),
        project_type: project_info.primary.clone(),
        framework: project_info.framework.clone(),
        package_manager: project_info.package_manager.clone(),
        hooks_installed,
        message,
    })
}

/// 生成配置文件内容
fn generate_config(project: &ProjectInfo) -> String {
    let framework = project.framework.as_deref().unwrap_or("");
    let package_manager = project.package_manager.as_deref().unwrap_or("");

    format!(
        r#"# TokenSlim Configuration
# Generated by `tokenslim init`
# Project type: {project_type}
# Framework: {framework}
# Package Manager: {package_manager}

[general]
# 项目类型 (自动检测)
project_type = "{project_type}"
# 框架 (如果检测到)
framework = "{framework}"
# 包管理器 (如果检测到)
package_manager = "{package_manager}"

[compression]
# 启用全局日志重排 (解决 make -jN 等并发构建的乱序问题)
reorder = true
# AI 导出模式 (生成面向大模型的降噪报告)
ai_export = false
# 预设配置: fast (速度优先), balanced (均衡), ai (AI 信号优先)
preset = "balanced"

[encoding]
# 强制 UTF-8 输出 (避免 Windows 下的编码问题)
force_utf8 = true

[plugins]
# 启用动态插件链 (允许多个插件连续处理同一文本)
plugin_chain = true

[token_optimizer]
# 全局 token 优化开关（字典经济模型）
enabled = true

[token_optimizer.scopes.paths]
# footer token 至少出现 N 次才写入 paths: 字典
min_footer_token_uses = 2
# 是否允许生成嵌套路径字典（如 $P7=$P3/subdir）
enable_nested_aliases = true

[token_optimizer.presets.fast.paths]
min_footer_token_uses = 2
enable_nested_aliases = false

[token_optimizer.presets.balanced.paths]
min_footer_token_uses = 2
enable_nested_aliases = true

[token_optimizer.presets.ai.paths]
min_footer_token_uses = 2
enable_nested_aliases = true
"#,
        project_type = project.primary,
        framework = framework,
        package_manager = package_manager,
    )
}

/// 简化的项目检测 (复用 doctor_workspace 的逻辑)
fn detect_project_type(cwd: &Path) -> ProjectInfo {
    let has = |name: &str| cwd.join(name).exists();
    let mut langs = Vec::<String>::new();

    if has("Cargo.toml") {
        langs.push("rust".to_string());
    }
    if has("pom.xml") || has("build.gradle") || has("build.gradle.kts") {
        langs.push("java".to_string());
    }
    if has("package.json") {
        langs.push("node".to_string());
    }
    if has("pyproject.toml") || has("requirements.txt") || has("setup.py") {
        langs.push("python".to_string());
    }
    if has("CMakeLists.txt") || has("Makefile") {
        langs.push("cpp".to_string());
    }
    if has("go.mod") {
        langs.push("go".to_string());
    }
    if has("Gemfile") {
        langs.push("ruby".to_string());
    }
    if has("composer.json") {
        langs.push("php".to_string());
    }
    if has("pubspec.yaml") {
        langs.push("dart".to_string());
    }
    if has("Package.swift") {
        langs.push("swift".to_string());
    }

    let primary = langs
        .first()
        .cloned()
        .unwrap_or_else(|| "unknown".to_string());
    let mut framework = None;
    let mut package_manager = None;

    // 检测 Node.js 框架和包管理器
    if primary == "node" {
        if has("pnpm-lock.yaml") {
            package_manager = Some("pnpm".to_string());
        } else if has("yarn.lock") {
            package_manager = Some("yarn".to_string());
        } else if has("bun.lockb") || has("bun.lock") {
            package_manager = Some("bun".to_string());
        } else {
            package_manager = Some("npm".to_string());
        }

        if has("next.config.js") || has("next.config.mjs") || has("next.config.ts") {
            framework = Some("nextjs".to_string());
        } else if has("vue.config.js") {
            framework = Some("vue".to_string());
        } else if has("nuxt.config.js") || has("nuxt.config.ts") {
            framework = Some("nuxt".to_string());
        } else if has("svelte.config.js") {
            framework = Some("svelte".to_string());
        } else if has("angular.json") {
            framework = Some("angular".to_string());
        }
    } else if primary == "rust" {
        if has("src-tauri/tauri.conf.json") {
            framework = Some("tauri".to_string());
        }
    } else if primary == "python" {
        let reqs = fs::read_to_string(cwd.join("requirements.txt")).unwrap_or_default();
        if has("manage.py") {
            framework = Some("django".to_string());
        } else if reqs.contains("fastapi") {
            framework = Some("fastapi".to_string());
        } else if reqs.contains("flask") {
            framework = Some("flask".to_string());
        }
    } else if primary == "dart" {
        if let Ok(content) = fs::read_to_string(cwd.join("pubspec.yaml")) {
            if content.contains("sdk: flutter") || content.contains("flutter:") {
                framework = Some("flutter".to_string());
            }
        }
    }

    ProjectInfo {
        primary,
        framework,
        package_manager,
    }
}

/// 简化的 shell 检测
fn detect_shell() -> String {
    // Windows 检测
    if cfg!(target_os = "windows") {
        if std::env::var("POWERSHELL_DISTRIBUTION_CHANNEL").is_ok() {
            return "powershell".to_string();
        }
        if std::env::var("SHELL")
            .map(|s| s.contains("bash"))
            .unwrap_or(false)
        {
            return "bash".to_string();
        }
        return "cmd".to_string();
    }

    // Unix 检测
    std::env::var("SHELL")
        .ok()
        .and_then(|s| {
            let shell = s.rsplit('/').next().unwrap_or("");
            match shell {
                "bash" | "zsh" | "fish" => Some(shell.to_string()),
                _ => None,
            }
        })
        .unwrap_or_else(|| "bash".to_string())
}

/// 简化的 hook 安装 (复用现有逻辑)
fn install_hooks_simple(shell: &str, dry_run: bool) -> Result<(), String> {
    // cmd 特殊处理：写 doskey 文件 + 设置 AutoRun 注册表
    if shell == "cmd" {
        return install_hooks_cmd(dry_run);
    }

    let shell_config = match shell {
        "bash" => ".bashrc",
        "zsh" => ".zshrc",
        "fish" => ".config/fish/config.fish",
        "powershell" => {
            if cfg!(target_os = "windows") {
                "Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
            } else {
                ".config/powershell/Microsoft.PowerShell_profile.ps1"
            }
        }
        _ => ".bashrc",
    };

    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".to_string());

    let config_path = Path::new(&home).join(shell_config);

    if dry_run {
        println!(
            "{}",
            t1("core_init_dry_run_install_path", config_path.display())
        );
        return Ok(());
    }

    // 检查配置文件是否存在
    if !config_path.exists() {
        // 创建空文件
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent).map_err(|e| format!("{E_INIT_CREATE_DIR}:{e}"))?;
        }
        fs::write(&config_path, "").map_err(|e| format!("{E_INIT_CREATE_CONFIG_FILE}:{e}"))?;
    }

    // 检查是否已经安装
    let content =
        fs::read_to_string(&config_path).map_err(|e| format!("{E_INIT_READ_CONFIG_FILE}:{e}"))?;

    if content.contains("# TokenSlim") {
        return Err(E_INIT_HOOKS_ALREADY_INSTALLED.to_string());
    }

    // 生成 hook 内容
    let hook_content = generate_hook_content(shell);

    // 追加到配置文件
    fs::write(&config_path, format!("{}\n{}", content, hook_content))
        .map_err(|e| format!("{E_INIT_APPEND_CONFIG_FILE}:{e}"))?;

    Ok(())
}

/// cmd (Windows) 钩子安装：写 doskey 宏文件 + 设置 AutoRun 注册表
fn install_hooks_cmd(dry_run: bool) -> Result<(), String> {
    let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".to_string());
    let hook_path = Path::new(&home).join("tokenslim_hook.cmd");

    // 检测当前 tokenslim 可执行文件路径，确保 doskey 宏能正确调用
    let tokenslim_exe = std::env::current_exe()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| "tokenslim".to_string());
    let tokenslim_cmd = if tokenslim_exe.ends_with(".exe") {
        tokenslim_exe
    } else {
        format!("{}.exe", tokenslim_exe)
    };

    if dry_run {
        println!(
            "{}",
            t1("core_init_dry_run_install_path", hook_path.display())
        );
        return Ok(());
    }

    // 检查是否已安装（通过 AutoRun 注册表）
    let reg_output = std::process::Command::new("reg")
        .args([
            "query",
            r"HKCU\Software\Microsoft\Command Processor",
            "/v",
            "AutoRun",
        ])
        .output();
    if let Ok(output) = reg_output {
        let stdout = String::from_utf8_lossy(&output.stdout);
        if stdout.contains("tokenslim_hook") {
            return Err(E_INIT_HOOKS_ALREADY_INSTALLED.to_string());
        }
    }

    // 写 doskey 宏文件（使用实际 tokenslim 路径）
    let hook_content = generate_hook_content_cmd(&tokenslim_cmd);
    fs::write(&hook_path, hook_content).map_err(|e| format!("{E_INIT_WRITE_HOOK_FILE}:{e}"))?;

    // 设置 AutoRun 注册表（追加到已有 AutoRun 之后）
    let existing = String::from_utf8_lossy(
        &std::process::Command::new("reg")
            .args([
                "query",
                r"HKCU\Software\Microsoft\Command Processor",
                "/v",
                "AutoRun",
            ])
            .output()
            .map(|o| o.stdout)
            .unwrap_or_default(),
    )
    .lines()
    .filter(|l| !l.trim().is_empty() && !l.starts_with("HKEY_") && !l.starts_with(' '))
    .last()
    .map(|l| l.trim().to_string())
    .unwrap_or_default();

    let auto_run_value = if existing.is_empty() {
        hook_path.to_string_lossy().to_string()
    } else {
        format!("{} && {}", existing, hook_path.display())
    };

    let status = std::process::Command::new("reg")
        .args([
            "add",
            r"HKCU\Software\Microsoft\Command Processor",
            "/v",
            "AutoRun",
            "/t",
            "REG_SZ",
            "/d",
            &auto_run_value,
            "/f",
        ])
        .status()
        .map_err(|e| format!("{E_INIT_SET_AUTORUN}:{e}"))?;

    if !status.success() {
        return Err(E_INIT_SET_AUTORUN_FAILED.to_string());
    }

    Ok(())
}

/// 生成 cmd hook 内容（使用实际 tokenslim 路径，避免 PATH 问题）
fn generate_hook_content_cmd(tokenslim_path: &str) -> String {
    format!(
        r#"@echo off
REM TokenSlim - AI Token Optimizer Hook
REM Auto-loaded via registry AutoRun.
REM doskey macros only effective in current cmd session (not subprocesses).
{}
{}
REM Aliases
doskey ts={tokenslim_path} $*
doskey ts-run={tokenslim_path} run $*
doskey ts-compress={tokenslim_path} compress $*
doskey ts-doctor={tokenslim_path} workspace $*
"#,
        VCS_COMMANDS
            .iter()
            .map(|c| format!("doskey {c}={tokenslim_path} run {c} $*"))
            .collect::<Vec<_>>()
            .join("\n"),
        BUILD_COMMANDS
            .iter()
            .map(|c| format!("doskey {c}={tokenslim_path} run {c} $*"))
            .collect::<Vec<_>>()
            .join("\n"),
    )
}

/// 生成 hook 内容（透明命令拦截 + 便捷别名）
pub fn generate_hook_content(shell: &str) -> String {
    match shell {
        "bash" | "zsh" => r#"
# TokenSlim - AI Token Optimizer Hook
# https://github.com/tokenslim/tokenslim
# --- VCS 透明拦截 ---
function git() { tokenslim run git "$@"; }
function svn() { tokenslim run svn "$@"; }
function hg() { tokenslim run hg "$@"; }
function p4() { tokenslim run p4 "$@"; }
function bzr() { tokenslim run bzr "$@"; }
function cvs() { tokenslim run cvs "$@"; }
function fossil() { tokenslim run fossil "$@"; }
function darcs() { tokenslim run darcs "$@"; }
function gh() { tokenslim run gh "$@"; }
function glab() { tokenslim run glab "$@"; }
function az() { tokenslim run az "$@"; }
function repo() { tokenslim run repo "$@"; }
# --- 构建工具透明拦截 ---
function cargo() { tokenslim run cargo "$@"; }
function make() { tokenslim run make "$@"; }
function cmake() { tokenslim run cmake "$@"; }
function gradle() { tokenslim run gradle "$@"; }
function gradlew() { tokenslim run gradlew "$@"; }
function mvn() { tokenslim run mvn "$@"; }
function npm() { tokenslim run npm "$@"; }
function yarn() { tokenslim run yarn "$@"; }
function pnpm() { tokenslim run pnpm "$@"; }
function pip() { tokenslim run pip "$@"; }
function pip3() { tokenslim run pip3 "$@"; }
function go() { tokenslim run go "$@"; }
function docker() { tokenslim run docker "$@"; }
function docker-compose() { tokenslim run docker-compose "$@"; }
function kubectl() { tokenslim run kubectl "$@"; }
function helm() { tokenslim run helm "$@"; }
function terraform() { tokenslim run terraform "$@"; }
function ansible() { tokenslim run ansible "$@"; }
function ansible-playbook() { tokenslim run ansible-playbook "$@"; }
function pulumi() { tokenslim run pulumi "$@"; }
function aws() { tokenslim run aws "$@"; }
function gcloud() { tokenslim run gcloud "$@"; }
function pytest() { tokenslim run pytest "$@"; }
function dotnet() { tokenslim run dotnet "$@"; }
function ninja() { tokenslim run ninja "$@"; }
function bazel() { tokenslim run bazel "$@"; }
function meson() { tokenslim run meson "$@"; }
function ctest() { tokenslim run ctest "$@"; }
function poetry() { tokenslim run poetry "$@"; }
function uv() { tokenslim run uv "$@"; }
function bun() { tokenslim run bun "$@"; }
function deno() { tokenslim run deno "$@"; }
function composer() { tokenslim run composer "$@"; }
function bundle() { tokenslim run bundle "$@"; }
function flutter() { tokenslim run flutter "$@"; }
function dart() { tokenslim run dart "$@"; }
function swift() { tokenslim run swift "$@"; }
function xcodebuild() { tokenslim run xcodebuild "$@"; }
# --- 便捷别名 ---
alias ts='tokenslim'
alias ts-run='tokenslim run'
alias ts-compress='tokenslim compress'
alias ts-doctor='tokenslim workspace'
"#
        .to_string(),
        "fish" => r#"
# TokenSlim - AI Token Optimizer Hook
function git; tokenslim run git $argv; end
function svn; tokenslim run svn $argv; end
function hg; tokenslim run hg $argv; end
function p4; tokenslim run p4 $argv; end
function bzr; tokenslim run bzr $argv; end
function cvs; tokenslim run cvs $argv; end
function fossil; tokenslim run fossil $argv; end
function darcs; tokenslim run darcs $argv; end
function gh; tokenslim run gh $argv; end
function glab; tokenslim run glab $argv; end
function az; tokenslim run az $argv; end
function repo; tokenslim run repo $argv; end
function cargo; tokenslim run cargo $argv; end
function make; tokenslim run make $argv; end
function cmake; tokenslim run cmake $argv; end
function gradle; tokenslim run gradle $argv; end
function gradlew; tokenslim run gradlew $argv; end
function mvn; tokenslim run mvn $argv; end
function npm; tokenslim run npm $argv; end
function yarn; tokenslim run yarn $argv; end
function pnpm; tokenslim run pnpm $argv; end
function pip; tokenslim run pip $argv; end
function pip3; tokenslim run pip3 $argv; end
function go; tokenslim run go $argv; end
function docker; tokenslim run docker $argv; end
function docker-compose; tokenslim run docker-compose $argv; end
function kubectl; tokenslim run kubectl $argv; end
function helm; tokenslim run helm $argv; end
function terraform; tokenslim run terraform $argv; end
function ansible; tokenslim run ansible $argv; end
function ansible-playbook; tokenslim run ansible-playbook $argv; end
function pulumi; tokenslim run pulumi $argv; end
function aws; tokenslim run aws $argv; end
function gcloud; tokenslim run gcloud $argv; end
function pytest; tokenslim run pytest $argv; end
function dotnet; tokenslim run dotnet $argv; end
function ninja; tokenslim run ninja $argv; end
function bazel; tokenslim run bazel $argv; end
function meson; tokenslim run meson $argv; end
function ctest; tokenslim run ctest $argv; end
function poetry; tokenslim run poetry $argv; end
function uv; tokenslim run uv $argv; end
function bun; tokenslim run bun $argv; end
function deno; tokenslim run deno $argv; end
function composer; tokenslim run composer $argv; end
function bundle; tokenslim run bundle $argv; end
function flutter; tokenslim run flutter $argv; end
function dart; tokenslim run dart $argv; end
function swift; tokenslim run swift $argv; end
function xcodebuild; tokenslim run xcodebuild $argv; end
alias ts 'tokenslim'
alias ts-run 'tokenslim run'
alias ts-compress 'tokenslim compress'
alias ts-doctor 'tokenslim workspace'
"#
        .to_string(),
        "powershell" => r#"
# TokenSlim - AI Token Optimizer Hook
# VCS
function git { tokenslim run git @args }
function svn { tokenslim run svn @args }
function hg { tokenslim run hg @args }
function p4 { tokenslim run p4 @args }
function bzr { tokenslim run bzr @args }
function cvs { tokenslim run cvs @args }
function fossil { tokenslim run fossil @args }
function darcs { tokenslim run darcs @args }
function gh { tokenslim run gh @args }
function glab { tokenslim run glab @args }
function az { tokenslim run az @args }
function repo { tokenslim run repo @args }
# Build
function cargo { tokenslim run cargo @args }
function make { tokenslim run make @args }
function cmake { tokenslim run cmake @args }
function gradle { tokenslim run gradle @args }
function gradlew { tokenslim run gradlew @args }
function mvn { tokenslim run mvn @args }
function npm { tokenslim run npm @args }
function yarn { tokenslim run yarn @args }
function pnpm { tokenslim run pnpm @args }
function pip { tokenslim run pip @args }
function pip3 { tokenslim run pip3 @args }
function go { tokenslim run go @args }
function docker { tokenslim run docker @args }
function docker-compose { tokenslim run docker-compose @args }
function kubectl { tokenslim run kubectl @args }
function helm { tokenslim run helm @args }
function terraform { tokenslim run terraform @args }
function ansible { tokenslim run ansible @args }
function ansible-playbook { tokenslim run ansible-playbook @args }
function pulumi { tokenslim run pulumi @args }
function aws { tokenslim run aws @args }
function gcloud { tokenslim run gcloud @args }
function pytest { tokenslim run pytest @args }
function dotnet { tokenslim run dotnet @args }
function ninja { tokenslim run ninja @args }
function bazel { tokenslim run bazel @args }
function meson { tokenslim run meson @args }
function ctest { tokenslim run ctest @args }
function poetry { tokenslim run poetry @args }
function uv { tokenslim run uv @args }
function bun { tokenslim run bun @args }
function deno { tokenslim run deno @args }
function composer { tokenslim run composer @args }
function bundle { tokenslim run bundle @args }
function flutter { tokenslim run flutter @args }
function dart { tokenslim run dart @args }
function swift { tokenslim run swift @args }
function xcodebuild { tokenslim run xcodebuild @args }
# Aliases
function ts { tokenslim @args }
function ts-run { tokenslim run @args }
function ts-compress { tokenslim compress @args }
function ts-doctor { tokenslim workspace @args }
"#
        .to_string(),
        "cmd" => generate_hook_content_cmd("tokenslim"), // fallback: 若未通过 install_hooks_cmd 调用
        _ => r#"
# TokenSlim - AI Token Optimizer Hook
# https://github.com/tokenslim/tokenslim
# Note: Unrecognized shell. Install with --hook-shell <name> to use presets.
# Manually add these aliases to your shell config:
alias ts='tokenslim'
alias ts-run='tokenslim run'
alias ts-compress='tokenslim compress'
alias ts-doctor='tokenslim workspace'
"#
        .to_string(),
    }
}

/// 项目信息 (简化版)
#[derive(Debug, Clone)]
pub struct ProjectInfo {
    pub primary: String,
    pub framework: Option<String>,
    pub package_manager: Option<String>,
}

/// 打印初始化结果摘要
pub fn print_init_summary(result: &InitResult) {
    println!("\n{}", t("core_init_summary_title"));
    println!("{}", t("core_init_summary_separator"));
    println!();

    if result.config_created {
        println!("{}", t1("core_init_config_created", &result.config_path));
    } else {
        println!(
            "{}",
            t1("core_init_config_existing_or_dry", &result.config_path)
        );
    }

    println!();
    println!("{}", t("core_init_project_detection"));
    println!("   {}", t1("core_init_project_type", &result.project_type));
    if let Some(fw) = &result.framework {
        println!("   {}", t1("core_init_project_framework", fw));
    }
    if let Some(pm) = &result.package_manager {
        println!("   {}", t1("core_init_project_package_manager", pm));
    }

    println!();
    if result.hooks_installed {
        println!("{}", t("core_init_hooks_installed"));
    } else {
        println!("{}", t("core_init_hooks_skipped"));
    }

    println!();
    println!("{}", t("core_init_next_steps"));
    println!("   {}", t("core_init_next_step1"));
    println!("   {}", t("core_init_next_step2"));
    println!("   {}", t("core_init_next_step3"));
    println!("   {}", t("core_init_next_step4"));
    println!("   {}", t("core_init_next_step5"));
    println!();

    let config_dir = std::path::Path::new("config").join("plugins");
    let capabilities =
        crate::core::plugin_config_loader::get_all_plugin_capabilities(if config_dir.exists() {
            Some(&config_dir)
        } else {
            None
        });
    if !capabilities.is_empty() {
        println!("🚀 Active Plugins:");
        let names: Vec<String> = capabilities.into_iter().map(|c| c.name).collect();
        println!("   {}", names.join(", "));
        println!();
    }
}
