#!/usr/bin/env python3
"""
generate_project.py - 根据 YAML 脚手架生成 Rust 项目

用法：
    python generate_project.py [yaml_dir] [output_dir]

默认：
    yaml_dir  = 当前目录
    output_dir = ./output
"""

import sys
import yaml
from pathlib import Path

# 项目基本信息
PROJECT_NAME = "TokenSlim"
PROJECT_VERSION = "0.1.0"
RUST_EDITION = "2021"

# 需要额外创建的顶层文件（模板）
README_TEMPLATE = f"""# {PROJECT_NAME}

AI 输入脱水压缩引擎 - 可逆压缩工具，用于减少大模型 token 消耗。

## 构建

```bash
cargo build --release
```

## 使用

```bash
# 压缩文件
{PROJECT_NAME} compress -i input.log -o compressed.json
# 解压缩
{PROJECT_NAME} decompress -i compressed.json -o output.log
```

更多选项请查看 `--help`。
"""

GITIGNORE_TEMPLATE = """# Generated by Cargo
/target/
**/*.rs.bk
Cargo.lock
"""

# 一些空文件的默认内容
DEFAULT_EMPTY_COMMENT = (
    "// This file is intentionally left empty (generated by scaffold).\n"
)


def ensure_dir(path):
    """确保目录存在"""
    Path(path).mkdir(parents=True, exist_ok=True)


def write_file(path, content):
    """写入文件，如果内容为 None 则写入默认空注释"""
    with open(path, "w", encoding="utf-8") as f:
        if content is None:
            f.write(DEFAULT_EMPTY_COMMENT)
        else:
            f.write(content)


def collect_yaml_files(yaml_dir):
    """收集指定目录下所有 .yaml 文件"""
    return list(Path(yaml_dir).glob("*.yaml"))


def parse_yaml(file_path):
    """解析单个 YAML 文件，返回模块信息字典（即 module 键对应的值）"""
    with open(file_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if "module" in data:
        return data["module"]
    else:
        print(f"警告：文件 {file_path} 缺少 'module' 键，将使用整个数据")
        return data

def generate_cargo_toml(dependencies):
    """生成 Cargo.toml 内容，兼容字典和字符串格式的依赖"""
    lines = [
        "[package]",
        f'name = "{PROJECT_NAME}"',
        f'version = "{PROJECT_VERSION}"',
        f'edition = "{RUST_EDITION}"',
        "",
        "[dependencies]",
    ]
    dep_dict = {}  # 用于去重

    for dep in dependencies:
        if isinstance(dep, dict):
            for name, spec in dep.items():
                if name in dep_dict:
                    continue
                if isinstance(spec, str):
                    lines.append(f'{name} = "{spec}"')
                elif isinstance(spec, dict):
                    items = []
                    for k, v in spec.items():
                        if k == "version":
                            items.append(f'version = "{v}"')
                        elif k == "features":
                            feats = ", ".join(f'"{f}"' for f in v)
                            items.append(f"features = [{feats}]")
                        else:
                            items.append(f"{k} = {v}")
                    deps_str = ", ".join(items)
                    lines.append(f"{name} = {{ {deps_str} }}")
                else:
                    lines.append(f'{name} = "{spec}"')
        elif isinstance(dep, str):
            # 处理字符串格式，如 "regex = 1.10"
            if "=" in dep:
                name, version = dep.split("=", 1)
                name = name.strip()
                version = version.strip().strip('"')
                if name in dep_dict:
                    continue
                lines.append(f'{name} = "{version}"')
            else:
                print(f"警告：无法解析依赖字符串 '{dep}'，将其作为 crate 名")
                if dep in dep_dict:
                    continue
                lines.append(f'{dep} = "*"')
        else:
            print(f"警告：未知依赖类型 {type(dep)}: {dep}")

    return "\n".join(lines)


def generate_lib_rs(modules):
    """生成 src/lib.rs，导出 core 和 plugins 模块（通过外部模块）"""
    lines = []
    # 检查 core 模块是否存在
    if any(m["path"].startswith("src/core/") for m in modules):
        lines.append("pub mod core;")
    # 检查 plugins 模块是否存在
    if any(m["path"].startswith("src/plugins/") for m in modules):
        lines.append("pub mod plugins;")
    # 检查 cli 模块是否存在
    if any(m["path"].startswith("src/cli") for m in modules):
        lines.append("pub mod cli;")
    # utils 模块总是存在（由脚本生成）
    lines.append("pub mod utils;")
    return "\n".join(lines)

def generate_core_mod_rs(modules):
    """生成 src/core/mod.rs，导出所有 core 子模块"""
    core_modules = [m for m in modules if m["path"].startswith("src/core/")]
    lines = []
    for m in core_modules:
        mod_name = m["name"]
        lines.append(f"pub mod {mod_name};")
    return "\n".join(lines)


def generate_plugins_mod_rs(modules):
    """生成 src/plugins/mod.rs，导出所有插件模块"""
    plugin_modules = [m for m in modules if m["path"].startswith("src/plugins/")]
    lines = []
    for m in plugin_modules:
        mod_name = m["name"]
        lines.append(f"pub mod {mod_name};")
    return "\n".join(lines)


def generate_main_rs():
    """生成 src/main.rs，调用 cli 模块"""
    return """use cli::{CliArgs, CliMode, run_compress, run_decompress};

fn main() {
    let args = match CliArgs::parse_args() {
        Ok(args) => args,
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(1);
        }
    };
    let result = match args.mode {
        CliMode::Compress => run_compress(&args),
        CliMode::Decompress => run_decompress(&args),
    };
    if let Err(e) = result {
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }
}
"""


def main():
    # 解析命令行参数
    yaml_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "./output"

    yaml_dir = Path(yaml_dir)
    output_dir = Path(output_dir)

    if not yaml_dir.exists():
        print(f"错误：YAML 目录 {yaml_dir} 不存在")
        sys.exit(1)

    # 收集所有 YAML 文件
    yaml_files = collect_yaml_files(yaml_dir)
    if not yaml_files:
        print(f"警告：在 {yaml_dir} 中没有找到 .yaml 文件")
        # 仍然继续，可能只生成基础结构

    modules = []
    all_deps = []

    for yf in yaml_files:
        print(f"处理 {yf.name}...")
        mod = parse_yaml(yf)
        modules.append(mod)
        # 收集依赖
        if "dependencies" in mod:
            all_deps.extend(mod["dependencies"])

    # 创建输出目录结构
    ensure_dir(output_dir)
    ensure_dir(output_dir / "src")
    ensure_dir(output_dir / "src/core")
    ensure_dir(output_dir / "src/plugins")
    ensure_dir(output_dir / "src/cli")
    ensure_dir(output_dir / "src/utils")
    ensure_dir(output_dir / "tests")
    ensure_dir(output_dir / "tests/fixtures")
    ensure_dir(output_dir / "examples")

    # 生成每个模块的文件
    for mod in modules:
        mod_path = output_dir / mod["path"]
        ensure_dir(mod_path)
        for file_info in mod["files"]:
            file_name = file_info["name"]
            file_content = file_info.get("content")
            file_path = mod_path / file_name
            write_file(file_path, file_content)

    # 生成顶层文件
    write_file(output_dir / "Cargo.toml", generate_cargo_toml(all_deps))
    write_file(output_dir / "README.md", README_TEMPLATE)
    write_file(output_dir / ".gitignore", GITIGNORE_TEMPLATE)

    # 生成 src/lib.rs
    write_file(output_dir / "src/lib.rs", generate_lib_rs(modules))

    # 生成 src/main.rs
    write_file(output_dir / "src/main.rs", generate_main_rs())

    # 生成 core/mod.rs
    core_mod_content = generate_core_mod_rs(modules)
    write_file(output_dir / "src/core/mod.rs", core_mod_content)

    # 生成 plugins/mod.rs
    plugins_mod_content = generate_plugins_mod_rs(modules)
    write_file(output_dir / "src/plugins/mod.rs", plugins_mod_content)

    # 生成 core/const.rs (空文件)
    write_file(
        output_dir / "src/core/const.rs", "// Core constants will be defined here.\n"
    )

    # 生成 utils/mod.rs, utils/fn.rs, utils/const.rs
    write_file(output_dir / "src/utils/mod.rs", "pub mod r#fn;\npub mod r#const;\n")
    write_file(output_dir / "src/utils/fn.rs", "// Utility functions.\n")
    write_file(output_dir / "src/utils/const.rs", "// Global constants.\n")

    # 生成测试占位文件
    write_file(output_dir / "tests/integration_test.rs", "// Integration tests.\n")
    # 可以创建一些示例 fixtures（用户自行添加）

    # 生成示例代码
    write_file(
        output_dir / "examples/simple_compress.rs", "// Example: compress a file.\n"
    )
    write_file(output_dir / "examples/cli_usage.rs", "// Example: CLI usage.\n")

    print(f"项目已生成在 {output_dir}")


if __name__ == "__main__":
    main()
